apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: hourly-tigera-policy-audit
spec:
  reportType: policy-audit
  schedule:  0 * * * *
  endpoints:
    namespaces:
      names: ["app-routable-demo"]
