apiVersion: v1
kind: Service
metadata:
  name: zone3
spec:
  ports:
  - name: echo-http
    port: 80
    protocol: TCP
  - name: echo-https
    port: 443
    protocol: TCP
  selector:
    app: echoserver

